Sequence of non-printing characters treatment

diff --git a/sh_prompt b/sh_prompt
--- a/sh_prompt
+++ b/sh_prompt
@@ -6,13 +6,10 @@
 # ----------------------------------------------------------------------
 
 _escseq() {
-        local esc="\e"
-        local code="$1"
-        if [ -n "$BASH_VERSION" ]; then
-                echo -e "\x01${esc}[${code}m\x02"
-        else
-                echo -e "\[${esc}[${code}m\]"
-        fi
+        esc="\e"
+        code="$1"
+        printf "${esc}[${code}m"
+        unset esc code
 }
 
 if [ -z ${NO_COLORS+x} ] && [ $(tput colors) -ge 8 ]; then
@@ -30,36 +27,36 @@ if [ -z ${NO_COLORS+x} ] && [ $(tput colors) -ge 8 ]; then
         # 7 -> White
 
         # Text attributes
-             RSTCOL="$(_escseq  0)"
-               BOLD="$(_escseq  1)"
-          UNDERLINE="$(_escseq  4)"
-              BLINK="$(_escseq  5)"
-            REVERSE="$(_escseq  7)"
-          CONCEALED="$(_escseq  8)"
+             RSTCOL="\[$(_escseq  0)\]"
+               BOLD="\[$(_escseq  1)\]"
+          UNDERLINE="\[$(_escseq  4)\]"
+              BLINK="\[$(_escseq  5)\]"
+            REVERSE="\[$(_escseq  7)\]"
+          CONCEALED="\[$(_escseq  8)\]"
 
         # Foreground colors
-           FG_BLACK="$(_escseq 30)"
-             FG_RED="$(_escseq 31)"
-           FG_GREEN="$(_escseq 32)"
-          FG_YELLOW="$(_escseq 33)"
-            FG_BLUE="$(_escseq 34)"
-         FG_MAGENTA="$(_escseq 35)"
-            FG_CYAN="$(_escseq 36)"
-           FG_WHITE="$(_escseq 37)"
+           FG_BLACK="\[$(_escseq 30)\]"
+             FG_RED="\[$(_escseq 31)\]"
+           FG_GREEN="\[$(_escseq 32)\]"
+          FG_YELLOW="\[$(_escseq 33)\]"
+            FG_BLUE="\[$(_escseq 34)\]"
+         FG_MAGENTA="\[$(_escseq 35)\]"
+            FG_CYAN="\[$(_escseq 36)\]"
+           FG_WHITE="\[$(_escseq 37)\]"
+
+        # Background colors
+           BG_BLACK="\[$(_escseq 40)\]"
+             BG_RED="\[$(_escseq 41)\]"
+           BG_GREEN="\[$(_escseq 42)\]"
+          BG_YELLOW="\[$(_escseq 43)\]"
+            BG_BLUE="\[$(_escseq 44)\]"
+         BG_MAGENTA="\[$(_escseq 45)\]"
+            BG_CYAN="\[$(_escseq 46)\]"
+           BG_WHITE="\[$(_escseq 47)\]"
 
         # Prompt colors
             P_HICOL="$FG_YELLOW"
           P_NORMCOL="$FG_CYAN"
-
-        # Background colors
-           BG_BLACK="$(_escseq 40)"
-             BG_RED="$(_escseq 41)"
-           BG_GREEN="$(_escseq 42)"
-          BG_YELLOW="$(_escseq 43)"
-            BG_BLUE="$(_escseq 44)"
-         BG_MAGENTA="$(_escseq 45)"
-            BG_CYAN="$(_escseq 46)"
-           BG_WHITE="$(_escseq 47)"
 else
         COLOR_SUPPORT=0
 fi
@@ -75,41 +72,43 @@ xterm*|screen*)
 esac
 
 _ps1_exit_status() {
-        local es="$?"
-        [ "$es" -ne 0 ] && echo -e "[\$?=${P_HICOL}${es}${P_NORMCOL}]-)"
+        es="$?"
+        [ "$es" -ne 0 ] && echo "[\$?=${es}]"
+        unset es
 }
 _ps1_sjobs() {
-        local sj="$(jobs | grep -vc Running)"
-        [ "$sj" -ne 0 ] && echo -e "[${P_HICOL}${sj}${P_NORMCOL} stopped]-"
+        sj="$(jobs | grep -vc Running)"
+        [ "$sj" -ne 0 ] && echo "[${sj} stopped]"
+        unset sj
 }
 _ps1_prjconf() {
-        [ -n "$PRJ_REF" ] && echo -e "[${P_HICOL}${PRJ_REF}${P_NORMCOL}]-"
+        [ -n "$PRJ_REF" ] && echo "[${PRJ_REF}]"
 }
 _ps1_check_vcs() {
         if [ "$PWD" != "$OWD" ]; then
                 OWD="$PWD"
                 if git rev-parse --git-dir > /dev/null 2>&1; then
-                        echo -e "[${P_HICOL}git${P_NORMCOL}]-"
+                        echo "[git]"
                 elif ls ./CVS > /dev/null 2>&1; then
-                        echo -e "[${P_HICOL}cvs${P_NORMCOL}]-"
+                        echo "[cvs]"
                 elif ls ./.SYNC > /dev/null 2>&1; then
-                        echo -e "[${P_HICOL}dss${P_NORMCOL}]-"
+                        echo "[dss]"
                 fi
         fi
 }
 _ps1_cwd() {
-        echo "[$PWD]" | sed -e "s#$HOME#~#; s#${G_WORSPACE-\0}#...#"
+        echo "[$PWD]" | sed -e "s#$HOME#~#; s#${G_WORKSPACE-\0}#\$G_WORKSPACE#"
 }
 
-# If this is an xterm, then set the title
-PS1="\033]0;[\s] [\w] [Last cmd: \"\$(tail -1 $HISTFILE)\"]\007"
-
 # Command line prompt
-PS1="${PS1}${P_NORMCOL}\n${PS1_HEAD}"                   # Prompt "head"
-PS1="${PS1}[\u@${P_HICOL}\h${P_NORMCOL}]-[\s]-"         # user@hostname / shell
-PS1="${PS1}\$(_ps1_exit_status)"                        # Last command exit status
-PS1="${PS1}\$(_ps1_sjobs)"                              # No. of stopped jobs
+PS1="${P_NORMCOL}\n${PS1_HEAD}"                         # Prompt "head"
+PS1="${PS1}[\u@${P_HICOL}\h${P_NORMCOL}]-[\s]"          # user@hostname / shell
+PS1="${PS1}${P_HICOL}\$(_ps1_exit_status)${P_NORMCOL}"  # Last command exit status (Mind: it *must* be the first command to be evaluated)
+PS1="${PS1}${P_HICOL}\$(_ps1_sjobs)${P_NORMCOL}"        # No. of stopped jobs
 PS1="${PS1}\$(_ps1_prjconf)"                            # Shell configured for a specific project?
 PS1="${PS1}\$(_ps1_check_vcs)"                          # In a VCS tree?
 PS1="${PS1}\$(_ps1_cwd)"                                # Current directory
 PS1="${PS1}\n${P_NORMCOL}${PS1_TAIL}[\!]-\$ ${RSTCOL}"  # Prompt "tail"
+
+# If this is an xterm, then set the title
+PS1="${PS1}\[\033]0;[\s] [\w] [Last cmd: \"\$(tail -1 $HISTFILE)\"]\007\]"
