Major restructuring, limited infobox for narrow terminals, first line no more wraps

diff --git a/sh_prompt b/sh_prompt
--- a/sh_prompt
+++ b/sh_prompt
@@ -8,7 +8,7 @@
 _escseq() {
         esc="\e"
         code="$1"
-        printf "${esc}[${code}m"
+        echo -e "${esc}[${code}m"
         unset esc code
 }
 
@@ -64,56 +64,51 @@ fi
 
 PS1_HEAD="..."
 PS1_TAIL='\`.....'
-[ -n "$DISPLAY" ] && case "$TERM" in
+[ -n "$DISPLAY" ] && [ "${LC_CTYPE%UTF-8}" != "$LC_CTYPE" ] &&
+case "$TERM" in
 xterm*|screen*)
         PS1_HEAD="┌──"
         PS1_TAIL="└─────"
         ;;
 esac
 
+# A complete prompt requires at least a 50-column wide terminal; for narrow
+# ones, revert to minimal infobox
 _ps1_exit_status() {
         es="$?"
-        [ "$es" -ne 0 ] && echo "-[\$?=${es}]-"
+        [ "$COLUMNS" -ge 50 ] && [ "$es" -ne 0 ] && echo "\$?=${es}, "
         unset es
 }
-_ps1_sjobs() {
-        sj="$(jobs | grep -vc Running)"
-        [ "$sj" -ne 0 ] && echo "-[S=${sj}]-"
-        unset sj
-}
 _ps1_prjconf() {
-        [ -n "$PRJ_REF" ] && echo "-[${PRJ_REF}]-"
+        [ "$COLUMNS" -ge 50 ] && [ -n "$PRJ_REF" ] && echo "${PRJ_REF}, "
 }
 _ps1_check_vcs() {
-        if [ "$PWD" != "$OWD" ]; then
-                OWD="$PWD"
-                if git rev-parse --git-dir > /dev/null 2>&1; then
-                        echo "-[git]-"
-                elif ls ./CVS > /dev/null 2>&1; then
-                        echo "-[cvs]-"
-                elif ls ./.SYNC > /dev/null 2>&1; then
-                        echo "-[dss]-"
+        if [ "$COLUMNS" -ge 50 ]; then
+                if [ -d CVS ]; then
+                        echo "cvs, "
+                elif [ -d .SYNC ]; then
+                        echo "dss, "
+                elif git rev-parse --git-dir > /dev/null 2>&1; then
+                        echo "git, "
                 fi
         fi
 }
-_ps1_cwd() {
-        echo "$PWD" | sed -e "s#$HOME#~#; s#$G_WORKSPACE#\$G_WORKSPACE#" |
-        awk -F "/" '{
-                if (length($0) > 32)
-                        $0 = "..." substr($0, length($0) - 28, length($0));
-                print "-[" $0 "]"
-        }'
+_ps1_noinfo() {
+        [ "$COLUMNS" -lt 50 ] && echo "*, "
 }
 
 # Command line prompt
-PS1="${P_NORMCOL}\n${PS1_HEAD}"                         # Prompt "head"
-PS1="${PS1}[\u@${P_HICOL}\h${P_NORMCOL}]--[\s]-"        # user@hostname / shell
-PS1="${PS1}${P_HICOL}\$(_ps1_exit_status)${P_NORMCOL}"  # Last command exit status (Mind: it *must* be the first command to be evaluated)
-PS1="${PS1}${P_HICOL}\$(_ps1_sjobs)${P_NORMCOL}"        # No. of stopped jobs
-PS1="${PS1}\$(_ps1_prjconf)"                            # Shell configured for a specific project?
-PS1="${PS1}\$(_ps1_check_vcs)"                          # In a VCS tree?
-PS1="${PS1}\$(_ps1_cwd)"                                # Current directory
-PS1="${PS1}\n${P_NORMCOL}${PS1_TAIL}[\!]--\$ ${RSTCOL}" # Prompt "tail"
+PS1="\[\033[?7l\]"                                      # Do not wrap prompt line
+PS1="${PS1}${P_NORMCOL}\n${PS1_HEAD}"                   # Prompt "head"
+PS1="${PS1}[\u@${P_HICOL}\h${P_NORMCOL}]-"              # user@hostname
+PS1="${PS1}[${P_HICOL}\$(_ps1_exit_status)${P_NORMCOL}" # Infobox: last command exit status
+PS1="${PS1}\$(_ps1_prjconf)"                            # Infobox: prj ref
+PS1="${PS1}${P_HICOL}\$(_ps1_check_vcs)${P_NORMCOL}"    # Infobox: in a VCS tree?
+PS1="${PS1}${P_HICOL}\$(_ps1_noinfo)${P_NORMCOL}"       # Infobox: no info for narrow terminals
+PS1="${PS1}\j jobs]-"                                   # Infobox: no. of managed jobs
+PS1="${PS1}[\W]"                                        # Current working directory
+PS1="${PS1}\n${P_NORMCOL}${PS1_TAIL} \$ ${RSTCOL}"      # Prompt "tail"
+PS1="${PS1}\[\033[?7h\]"                                # Restore line wrapping
 
 # If this is an xterm, then set the title
 PS1="${PS1}\[\033]0;[\s] [\w] [Last cmd: \"\$(tail -1 $HISTFILE)\"]\007\]"
